name: Build sdist and bdist on Tag Pushed

on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Build wheel ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ ubuntu-22.04, manylinux_x86_64 ]
          - [ ubuntu-22.04, musllinux_x86_64 ]
          - [ macos-13, macosx_x86_64 ]
          - [ macos-14, macosx_arm64 ]
          - [ windows-2019, win_amd64 ]
          - [ windows-2019, win32 ]
        python: [ "cp310","cp311", "cp312", "cp313" ]
    steps:
      - name: Checkout pyquadkey2
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build Wheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -v {project} --import-mode=importlib

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl

      - name: Publish Wheel
        uses: softprops/action-gh-release@v2
        with:
          files: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pyquadkey2
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: build
        run: |
          python3 -m pip install build
          python3 -m build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

      - name: Publish Wheel
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*